-- Generated by the database client.
CREATE TABLE webglass_bot (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    phone text,
    step integer,
    name text,
    email text,
    role text,
    last_message_id text,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    kanban_step integer DEFAULT 0,
    avatar text,
    PRIMARY KEY(id)
);
CREATE UNIQUE INDEX webglass_bot_phone_unique ON public.webglass_bot USING btree (phone);
